from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates

import json
import platform
import time
from datetime import datetime

import psutil
import requests

from app.rag import retrieve_context
from app.docker_monitor import get_docker_metrics
from app.telemetry_history import record_telemetry, get_history


# ============================================================
# DEVPULSE NEXUS
# AI-Powered Developer Environment Observability
# and AIDevOps Intelligence
# ============================================================

app = FastAPI(
    title="DevPulse Nexus",
    description=(
        "AI-powered developer environment observability, "
        "Digital Twin telemetry, Docker monitoring, and "
        "RAG-based troubleshooting."
    ),
    version="1.0.0",
)

templates = Jinja2Templates(directory="templates")


# ============================================================
# CONFIGURATION
# ============================================================

OLLAMA_URL = "http://127.0.0.1:11434/api/generate"
OLLAMA_MODEL = "qwen2.5:1.5b"

# Keep generation moderate because the model is running locally.
OLLAMA_NUM_PREDICT = 160

# Number of RAG documents to retrieve.
RAG_RESULTS = 2

# Maximum time allowed for Ollama to respond.
OLLAMA_TIMEOUT = 120

# Conservative Docker container memory signal.
# A container using >= 20% of its Docker memory limit is
# considered potentially significant.
SIGNIFICANT_CONTAINER_MEMORY_PERCENT = 20.0


# ============================================================
# UTILITY
# ============================================================

def now_iso():
    """Return the current local timestamp."""

    return datetime.now().isoformat()


# ============================================================
# SYSTEM TELEMETRY
# ============================================================

def get_system_telemetry():
    """
    Collect live host-level telemetry.

    This is observational data.
    It is not generated by the AI model.
    """

    memory = psutil.virtual_memory()
    disk = psutil.disk_usage("/")

    return {
        "platform": platform.system(),
        "kernel": platform.release(),

        "cpu": {
            "usage_percent": psutil.cpu_percent(interval=0.3),
            "cores": psutil.cpu_count() or 0,
        },

        "memory": {
            "total_gb": round(
                memory.total / (1024 ** 3),
                2,
            ),
            "used_gb": round(
                memory.used / (1024 ** 3),
                2,
            ),
            "available_gb": round(
                memory.available / (1024 ** 3),
                2,
            ),
            "usage_percent": memory.percent,
        },

        "disk": {
            "total_gb": round(
                disk.total / (1024 ** 3),
                2,
            ),
            "used_gb": round(
                disk.used / (1024 ** 3),
                2,
            ),
            "free_gb": round(
                disk.free / (1024 ** 3),
                2,
            ),
            "usage_percent": disk.percent,
        },
    }


# ============================================================
# DIGITAL TWIN
# ============================================================

def get_digital_twin():
    """
    Build a point-in-time representation of the
    developer environment.

    The Digital Twin combines:

    - host telemetry
    - Docker telemetry
    """

    return {
        "timestamp": now_iso(),
        "system": get_system_telemetry(),
        "docker": get_docker_metrics(),
    }


# ============================================================
# MEMORY PARSING
# ============================================================

def parse_memory_percentage(value):
    """
    Convert Docker memory percentage strings such as:

        '0.26%'

    into a float.

    Invalid values safely become 0.0.
    """

    if value is None:
        return 0.0

    try:
        return float(
            str(value)
            .replace("%", "")
            .strip()
        )

    except (ValueError, TypeError):
        return 0.0


# ============================================================
# DETERMINISTIC DIAGNOSIS
# ============================================================

def build_diagnosis(digital_twin):
    """
    Produce a deterministic diagnosis from telemetry.

    IMPORTANT:

    This function runs BEFORE the LLM.

    The LLM explains the diagnosis.
    The LLM does not determine the diagnosis.
    """

    system = digital_twin.get("system", {})
    memory = system.get("memory", {})
    docker = digital_twin.get("docker", {})

    host_memory_usage = memory.get(
        "usage_percent",
        0,
    )

    # --------------------------------------------------------
    # Docker unavailable
    # --------------------------------------------------------

    if not docker.get("available", False):

        return {
            "docker_status": "unavailable",

            "running_containers": None,

            "docker_container_memory": "unknown",

            "host_memory_usage_percent":
                host_memory_usage,

            "docker_is_evidently_responsible":
                "unknown",

            "assessment":
                "unknown",

            "significant_containers":
                [],

            "reason": (
                "Docker telemetry is unavailable. "
                "Docker container memory usage cannot "
                "currently be evaluated."
            ),
        }

    # --------------------------------------------------------
    # Docker available
    # --------------------------------------------------------

    containers = docker.get(
        "containers",
        [],
    )

    container_count = docker.get(
        "container_count",
        len(containers),
    )

    # --------------------------------------------------------
    # No containers
    # --------------------------------------------------------

    if container_count == 0:

        return {
            "docker_status": "available",

            "running_containers": 0,

            "docker_container_memory": "none",

            "host_memory_usage_percent":
                host_memory_usage,

            "docker_is_evidently_responsible":
                False,

            "assessment":
                "not_responsible",

            "significant_containers":
                [],

            "reason": (
                "No Docker containers are currently "
                "running, so the current host memory "
                "usage cannot be attributed to running "
                "Docker containers."
            ),
        }

    # --------------------------------------------------------
    # Containers exist
    # --------------------------------------------------------

    container_memory = []
    significant_containers = []

    for container in containers:

        name = container.get(
            "name",
            "unknown",
        )

        memory_usage = container.get(
            "memory_usage",
            "unknown",
        )

        memory_percent_raw = container.get(
            "memory_percent",
            "0%",
        )

        memory_percent = parse_memory_percentage(
            memory_percent_raw
        )

        container_info = {
            "name": name,
            "memory_usage": memory_usage,
            "memory_percent": memory_percent_raw,
        }

        container_memory.append(
            container_info
        )

        # ----------------------------------------------------
        # Conservative container signal
        # ----------------------------------------------------

        if (
            memory_percent
            >= SIGNIFICANT_CONTAINER_MEMORY_PERCENT
        ):

            significant_containers.append(
                {
                    "name": name,
                    "memory_percent": memory_percent,
                }
            )

    # --------------------------------------------------------
    # Significant container utilization
    # --------------------------------------------------------

    if significant_containers:

        return {
            "docker_status": "available",

            "running_containers":
                container_count,

            "docker_container_memory":
                container_memory,

            "host_memory_usage_percent":
                host_memory_usage,

            "docker_is_evidently_responsible":
                "potentially",

            "assessment":
                "potentially_significant",

            "significant_containers":
                significant_containers,

            "reason": (
                "One or more Docker containers show "
                "comparatively high memory utilization "
                "relative to their configured Docker "
                "memory limit. Docker may be contributing "
                "to resource pressure, but the available "
                "telemetry does not prove that Docker is "
                "the sole cause of host memory usage."
            ),
        }

    # --------------------------------------------------------
    # Containers running but low utilization
    # --------------------------------------------------------

    return {
        "docker_status": "available",

        "running_containers":
            container_count,

        "docker_container_memory":
            container_memory,

        "host_memory_usage_percent":
            host_memory_usage,

        "docker_is_evidently_responsible":
            False,

        "assessment":
            "unlikely",

        "significant_containers":
            [],

        "reason": (
            "Docker containers are running, but their "
            "observed memory utilization is low. Docker "
            "is therefore unlikely to be the primary "
            "cause of the current host memory usage."
        ),
    }


# ============================================================
# RAG CONTEXT
# ============================================================

def get_knowledge(question):
    """
    Retrieve technical knowledge relevant to the user's
    question.
    """

    try:

        documents = retrieve_context(
            question,
            number_of_results=RAG_RESULTS,
        )

        if not documents:
            return []

        return documents

    except Exception as exc:

        print(
            f"RAG retrieval error: {exc}"
        )

        return []


# ============================================================
# PROMPT BUILDER
# ============================================================

def build_prompt(
    question,
    digital_twin,
    diagnosis,
    documents,
):
    """
    Build a grounded prompt.

    Telemetry and deterministic diagnosis are explicitly
    authoritative.
    """

    context = (
        "\n\n".join(documents)
        if documents
        else "No relevant knowledge was retrieved."
    )

    telemetry_json = json.dumps(
        digital_twin,
        indent=2,
    )

    diagnosis_json = json.dumps(
        diagnosis,
        indent=2,
    )

    return f"""
You are DevPulse Nexus.

You are an AI-powered developer environment
observability and AIDevOps intelligence assistant.

Your responsibility is to explain the current
developer environment using:

1. LIVE DIGITAL TWIN TELEMETRY
2. DETERMINISTIC DIAGNOSIS
3. RETRIEVED TECHNICAL KNOWLEDGE

============================================================
CRITICAL RULES
============================================================

The LIVE TELEMETRY is authoritative.

The DETERMINISTIC DIAGNOSIS is authoritative.

The retrieved knowledge is supporting technical context.

You MUST NOT contradict the deterministic diagnosis.

You MUST NOT invent:

- containers
- processes
- memory values
- CPU values
- disk values
- resource limits
- errors
- causes
- configuration
- workloads

If the telemetry does not prove a cause, explicitly say:

"The exact cause cannot be determined from the
available telemetry."

Do not present speculation as fact.

Do not automatically blame Docker for host memory usage.

If running_containers is 0:

Docker containers are NOT responsible for the observed
host memory usage.

If containers are running but their observed memory
utilization is low:

Explain that Docker is unlikely to be the primary cause.

If the deterministic diagnosis says Docker may be
contributing:

Explain that Docker may be contributing, while making
clear that the telemetry does not prove sole causation.

IMPORTANT:

Do not describe ordinary host memory utilization as
a problem unless the telemetry or user question provides
evidence that it is problematic.

Always distinguish:

OBSERVED FACTS

from

LIKELY / POSSIBLE CAUSES.

============================================================
LIVE DIGITAL TWIN
============================================================

{telemetry_json}

============================================================
DETERMINISTIC DIAGNOSIS
============================================================

{diagnosis_json}

============================================================
RETRIEVED TECHNICAL KNOWLEDGE
============================================================

{context}

============================================================
USER QUESTION
============================================================

{question}

============================================================
RESPONSE FORMAT
============================================================

OBSERVED:

- Describe only relevant live telemetry.
- Mention Docker/container state when relevant.

LIKELY CAUSE:

- Explain what the telemetry supports.
- Do not invent a cause.
- If the exact cause is unknown, say so.
- Do not blame Docker without telemetry evidence.

RECOMMENDATION:

- Give practical troubleshooting steps.
- Use retrieved knowledge where relevant.
- Do not recommend actions unsupported by the
  available information.

Keep the response concise and technically useful.

Never contradict the deterministic diagnosis.
"""


# ============================================================
# OLLAMA
# ============================================================

def ask_ollama(prompt):
    """
    Send the grounded prompt to the local Ollama model.

    Returns:

        answer
        latency_seconds
    """

    start = time.perf_counter()

    response = requests.post(
        OLLAMA_URL,

        json={
            "model": OLLAMA_MODEL,

            "prompt": prompt,

            "stream": False,

            "options": {
                "num_predict":
                    OLLAMA_NUM_PREDICT
            },
        },

        timeout=OLLAMA_TIMEOUT,
    )

    response.raise_for_status()

    result = response.json()

    latency = round(
        time.perf_counter() - start,
        2,
    )

    answer = result.get(
        "response",
        "",
    ).strip()

    if not answer:

        answer = (
            "The local AI model returned an empty response."
        )

    return answer, latency


# ============================================================
# HOME
# ============================================================

@app.get(
    "/",
    response_class=HTMLResponse,
)
def home(request: Request):

    return templates.TemplateResponse(
        request=request,
        name="index.html",
        context={},
    )


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/health")
def health():

    return {
        "status": "ok",
        "service": "DevPulse Nexus",
        "version": "1.0.0",
        "ollama_model": OLLAMA_MODEL,
    }


# ============================================================
# DIGITAL TWIN API
# ============================================================

@app.get("/digital-twin")
def digital_twin():

    snapshot = get_digital_twin()

    # Every Digital Twin request becomes a history point.
    record_telemetry(snapshot)

    return snapshot


# ============================================================
# TELEMETRY API
# ============================================================

@app.get("/telemetry")
def telemetry():

    return get_system_telemetry()


# ============================================================
# DOCKER API
# ============================================================

@app.get("/docker")
def docker():

    return get_docker_metrics()


# ============================================================
# HISTORY API
# ============================================================

@app.get("/history")
def history(limit: int = 120):
    """
    Return previously recorded Digital Twin snapshots.

    A fresh snapshot is NOT created here.
    This prevents /history from unexpectedly changing
    the telemetry history.
    """

    records = get_history(limit)

    return {
        "count": len(records),
        "records": records,
    }


# ============================================================
# DIAGNOSIS API
# ============================================================

@app.get("/diagnosis")
def diagnosis():

    twin = get_digital_twin()

    result = build_diagnosis(twin)

    return {
        "timestamp": twin["timestamp"],
        "diagnosis": result,
        "digital_twin": twin,
    }


# ============================================================
# ASK API
# ============================================================

@app.get("/ask")
def ask(question: str):

    question = question.strip()

    # --------------------------------------------------------
    # Validate question
    # --------------------------------------------------------

    if not question:

        return {
            "question": question,

            "answer": (
                "Please provide a developer or DevOps "
                "question."
            ),

            "diagnosis": None,

            "digital_twin": None,

            "sources": [],

            "ai": {
                "model": OLLAMA_MODEL,
                "latency_seconds": None,
                "error": None,
            },
        }

    # --------------------------------------------------------
    # 1. Collect live environment telemetry
    # --------------------------------------------------------

    digital_twin = get_digital_twin()

    # Record the snapshot because /ask is also an
    # observability event.
    record_telemetry(digital_twin)

    # --------------------------------------------------------
    # 2. Produce deterministic diagnosis
    # --------------------------------------------------------

    diagnosis = build_diagnosis(
        digital_twin
    )

    # --------------------------------------------------------
    # 3. Retrieve relevant knowledge
    # --------------------------------------------------------

    documents = get_knowledge(
        question
    )

    # --------------------------------------------------------
    # 4. Build grounded prompt
    # --------------------------------------------------------

    prompt = build_prompt(
        question=question,
        digital_twin=digital_twin,
        diagnosis=diagnosis,
        documents=documents,
    )

    # --------------------------------------------------------
    # 5. Ask local AI model
    # --------------------------------------------------------

    ai_error = None
    latency = None

    try:

        answer, latency = ask_ollama(
            prompt
        )

    except requests.exceptions.Timeout:

        ai_error = (
            "The local AI model timed out. "
            "Live telemetry and deterministic diagnosis "
            "are still available."
        )

        answer = (
            "The local AI model took too long to respond. "
            "Review the returned diagnosis and Digital Twin "
            "telemetry for the current environment state."
        )

    except requests.exceptions.ConnectionError:

        ai_error = (
            "Could not connect to Ollama at "
            f"{OLLAMA_URL}."
        )

        answer = (
            "The local AI model is unavailable. "
            "Make sure Ollama is running and the configured "
            f"model '{OLLAMA_MODEL}' is available."
        )

    except requests.exceptions.HTTPError as exc:

        ai_error = str(exc)

        answer = (
            "Ollama returned an HTTP error while processing "
            "the request. The deterministic diagnosis and "
            "Digital Twin telemetry are still available."
        )

    except requests.exceptions.RequestException as exc:

        ai_error = str(exc)

        answer = (
            "The local AI model could not process the request. "
            "The deterministic diagnosis and Digital Twin "
            "telemetry are still available."
        )

    except Exception as exc:

        ai_error = str(exc)

        print(
            f"Ollama unexpected error: {exc}"
        )

        answer = (
            "An unexpected error occurred while generating "
            "the AI response. The deterministic diagnosis "
            "and Digital Twin telemetry are still available."
        )

    # --------------------------------------------------------
    # 6. Return complete observability response
    # --------------------------------------------------------

    return {
        "question": question,

        "answer": answer,

        "diagnosis": diagnosis,

        "digital_twin": digital_twin,

        "sources": documents,

        "ai": {
            "model": OLLAMA_MODEL,
            "latency_seconds": latency,
            "error": ai_error,
        },
    }
